"""add_display_type_to_notes

Revision ID: 480118763c46
Revises: abf082dc8a0a
Create Date: 2026-08-21 23:21:24.056631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480118763c46'
down_revision: Union[str, None] = 'abf082dc8a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notes', sa.Column('display_type', sa.String(length=50), server_default='RANDOM', nullable=False))
    op.add_column('user_notes', sa.Column('target_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_notes', 'target_date')
    op.drop_column('user_notes', 'display_type')
    # ### end Alembic commands ###
