"""add_user_notes_table

Revision ID: abf082dc8a0a
Revises: c82bbeaa8201
Create Date: 2026-08-21 23:19:21.658960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf082dc8a0a'
down_revision: Union[str, None] = 'c82bbeaa8201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
