"""add_special_events_table

Revision ID: c82bbeaa8201
Revises: 1041d1981f84
Create Date: 2026-08-21 23:01:36.095222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82bbeaa8201'
down_revision: Union[str, None] = '1041d1981f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('recurrence_type', sa.String(length=50), nullable=False),
    sa.Column('interval_value', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_events_user_id'), 'special_events', ['user_id'], unique=False)
    
    # Direct SQL Seed inside Migration for May 22, 2022
    op.execute("""
        INSERT INTO special_events (id, user_id, title, anchor_date, recurrence_type, interval_value, category, description, created_at, updated_at)
        SELECT 
            gen_random_uuid(), 
            u.id, 
            'Kỷ niệm ngày bên nhau ✨', 
            '2022-05-22', 
            'EVERY_N_DAYS', 
            100, 
            'love', 
            'Tự động tính mốc 100, 200, 300... ngày yêu',
            NOW(), 
            NOW()
        FROM users u
        WHERE u.email = 'khanhnd05@gmail.com'
        AND NOT EXISTS (
            SELECT 1 FROM special_events se 
            WHERE se.user_id = u.id AND se.anchor_date = '2022-05-22' AND se.recurrence_type = 'EVERY_N_DAYS'
        );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_special_events_user_id'), table_name='special_events')
    op.drop_table('special_events')
    # ### end Alembic commands ###
